//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class tyayin
    {
        public int id { get; set; }
        public string yayn { get; set; }
        public string ktp { get; set; }
        public string ktgr { get; set; }
    }
}
